/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.infox.telas;

import br.com.infox.dal.ModuloConexao;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ander
 */
public class Tela_1_Logar_Direto extends javax.swing.JPanel {

    Connection conexao = null;//variável criada no modulo de conexao
    PreparedStatement pst = null; //Framework para instrução sql
    ResultSet rs = null;

    /**
     * Creates new form Tela1
     */
    public Tela_1_Logar_Direto() {
        initComponents();
        conexao = ModuloConexao.conector();
        System.out.println(conexao);
        criarUserTest();
    }

    public void criarUserTest() {
        //Alinha abaixo: ESSA LINHA SERVE PARA INSERIR UM USUÁRIO TESTE
        String sql = " replace into tbusuarios values (9999, 'TESTE', '', '','', 'admin'); ";
        try {
            pst = conexao.prepareStatement(sql);
            pst.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public static void main(String[] args) {
        Tela_1_Logar_Direto INICIALIZAR = new Tela_1_Logar_Direto();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaLogin login = new TelaLogin();
                login.setVisible(true);
                login.logar();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
